<a href="https://colab.research.google.com/github/Kyoung-mii/DeepLearning/blob/main/03_DeepLearningFramwork%20/3_2_usingTensorsInTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3-3 [1] 필요한 패키지 불러오기

In [1]:
import tensorflow as tf
import numpy as np

# 3-3 [2] 상수 텐서


In [4]:
a = tf.constant(10.)
b = tf.constant([1, 2, 3, 4])
c = tf.constant([[[1, 2], [3, 4], [5, 6]],
                 [[7, 8], [9, 10], [11, 12]],
                 [[13, 14], [15, 16], [17, 18]],
                 [[19, 20], [21, 22], [23, 24]]], dtype = tf.float32)
print('a : dtype = ',a.dtype, '\n',a)
print('b : shape = ',b.shape, '\n',b)
print('c : device = ', c.device)

a : dtype =  <dtype: 'float32'> 
 tf.Tensor(10.0, shape=(), dtype=float32)
b : shape =  (4,) 
 tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
c : device =  /job:localhost/replica:0/task:0/device:CPU:0


# 3-3 [3] 변수 텐서

In [6]:
x = tf.Variable(10.)
y = tf.Variable([[1., 2., 3.],[4., 5., 6.]])
z = np.array([[1., 3.], [2., 4.], [3., 5.]], dtype = np.float32)
print('x:dtype = ', x.dtype, '\n', x)
print('y:shape = ', y.shape, '\n', y)
print('y: device = ', y.device)

x:dtype =  <dtype: 'float32'> 
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>
y:shape =  (2, 3) 
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
y: device =  /job:localhost/replica:0/task:0/device:CPU:0


# 3-3 [4] 변수 텐서에 값을 대입하기

In [8]:
x.assign_add(20.0)
print('x = ', x.numpy())

x =  32.0


# 3-3 [5] 텐서에 대한 산술 연산 및 수학 함수

In [9]:
print('a * b =', (a * tf.cast(b, tf.float32)).numpy())
print('tf.math.exp(y) =', tf.exp(y))
print('tf.math.reduce_sum(c, axis = 2) = ', tf.reduce_sum(c, axis = 2))

a * b = [10. 20. 30. 40.]
tf.math.exp(y) = tf.Tensor(
[[  2.7182817   7.389056   20.085537 ]
 [ 54.59815   148.41316   403.4288   ]], shape=(2, 3), dtype=float32)
tf.math.reduce_sum(c, axis = 2) =  tf.Tensor(
[[ 3.  7. 11.]
 [15. 19. 23.]
 [27. 31. 35.]
 [39. 43. 47.]], shape=(4, 3), dtype=float32)


# 3-3 [6] 선형대수 연산 및 묵시적 형 변환

In [11]:
print('tf.linalg.matmul(y,z)=')
print(tf.matmul(y,z))
print('np.matmul(y, z)=')
print(np.matmul(y,z))

tf.linalg.matmul(y,z)=
tf.Tensor(
[[14. 26.]
 [32. 62.]], shape=(2, 2), dtype=float32)
np.matmul(y, z)=
[[14. 26.]
 [32. 62.]]
